import { Project, DmLog } from './types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    name: '24년 가을 신상품 협업 제안',
    projectType: '협찬',
    brand: '모던웨어 스튜디오',
    tag: '#CH_24FW',
    status: 'active',
    statusText: '기록 활성',
    iconType: 'hanger',
    totalSent: 10,
    repliedCount: 8,
    confirmedCount: 4,
    latestLog: {
      handle: '@stylist_minji',
      action: '협업 성사',
      timeAgo: '1분 전',
    },
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01 00:00:00',
    description: '2026 F/W 시즌 모던웨어 룩북 릴스 및 피드 협업 제안 캠페인',
  },
  {
    id: 'proj_2',
    name: '뷰티 라인업 앰버서더 2기',
    projectType: '광고',
    brand: '글로우 래보라토리스',
    tag: '#GLOW_AMBASSADOR',
    status: 'waiting',
    statusText: '진행 중',
    iconType: 'leaf',
    totalSent: 6,
    repliedCount: 5,
    confirmedCount: 2,
    latestLog: {
      handle: '@beauty_som',
      action: '소통 중',
      timeAgo: '6분 전',
    },
    createdAt: '2026-09-03',
    updatedAt: '2026-09-03 00:00:00',
    description: '수분 진정 앰플 런칭 기념 뷰티 인플루언서 50인 시딩 프로그램',
  },
  {
    id: 'proj_3',
    name: 'F/W 시즌 아우터 인플루언서 시딩',
    projectType: '협찬',
    brand: '어반클라우드',
    tag: '#URBAN_OUTER',
    status: 'waiting',
    statusText: '진행 중',
    iconType: 'bag',
    totalSent: 5,
    repliedCount: 4,
    confirmedCount: 2,
    latestLog: {
      handle: '@urban_lookbook',
      action: '협업 성사',
      timeAgo: '28분 전',
    },
    createdAt: '2026-09-05',
    updatedAt: '2026-09-05 00:00:00',
    description: '어반클라우드 헤비 아우터 3종 스타일링 OOTD 착장 피드 제안',
  },
  {
    id: 'proj_4',
    name: '추석 얼리버드 앰버서더',
    projectType: '공동구매',
    brand: '루미너스 웰니스',
    tag: '#LUMI_HARVEST',
    status: 'paused',
    statusText: '수집 일시정지',
    iconType: 'sparkles',
    totalSent: 4,
    repliedCount: 3,
    confirmedCount: 2,
    latestLog: {
      handle: '@seoul_look_archive',
      action: '협업 성사',
      timeAgo: '2시간 전',
    },
    createdAt: '2026-09-08',
    updatedAt: '2026-09-08 00:00:00',
    description: '명절 프리미엄 기프트 세트 사전 홍보 인플루언서 제안',
  },
];

export const INITIAL_DM_LOGS: DmLog[] = [
  // --- proj_1 (10건) ---
  {
    id: 'log_1',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 14:38:12',
    timeAgo: '1분 전',
    influencer: {
      handle: 'stylist_minji',
      nickname: '민지',
      profileUrl: 'https://instagram.com/stylist_minji',
      followers: '45.2K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email_inpock',
    secondMessageSent: true,
    memo: '9/15 릴스 업로드 확정, 가이드 전달 완료',
  },
  {
    id: 'log_3',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 14:25:40',
    timeAgo: '14분 전',
    influencer: {
      handle: 'daily_ootd_fit',
      nickname: '데일리핏',
      profileUrl: 'https://instagram.com/daily_ootd_fit',
      followers: '24.1K',
      verified: false,
    },
    status: 'waiting',
    channel: 'none',
    secondMessageSent: false,
    memo: '2차 리마인드 DM 발송 예정 (익일 오전)',
  },
  {
    id: 'log_5',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 13:57:49',
    timeAgo: '42분 전',
    influencer: {
      handle: 'k_fashion_daily',
      nickname: '케이패션',
      profileUrl: 'https://instagram.com/k_fashion_daily',
      followers: '15.6K',
      verified: false,
    },
    status: 'rejected',
    channel: 'email',
    secondMessageSent: false,
    memo: '일정 조율 불가로 이번 시즌 제외',
  },
  {
    id: 'log_7',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 13:28:10',
    timeAgo: '1시간 전',
    influencer: {
      handle: 'fashion_chloe',
      nickname: '클로이',
      profileUrl: 'https://instagram.com/fashion_chloe',
      followers: '98.4K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email_inpock',
    secondMessageSent: true,
    memo: '스토리 3회 + 릴스 1회 패키지 조율 완료',
  },
  {
    id: 'log_9',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 13:02:45',
    timeAgo: '1시간 전',
    influencer: {
      handle: 'ootd_haru',
      nickname: '하루',
      profileUrl: 'https://instagram.com/ootd_haru',
      followers: '19.3K',
      verified: false,
    },
    status: 'waiting',
    channel: 'email',
    secondMessageSent: false,
    memo: 'DM 확인 후 회신 준다고 함',
  },
  {
    id: 'log_11',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 12:18:30',
    timeAgo: '2시간 전',
    influencer: {
      handle: 'daily_fashion_k',
      nickname: '데일리케이',
      profileUrl: 'https://instagram.com/daily_fashion_k',
      followers: '37.8K',
      verified: false,
    },
    status: 'in_talks',
    channel: 'inpock',
    secondMessageSent: true,
    memo: '착장 아우터 컬러 옵션(브라운/블랙) 논의 중',
  },
  {
    id: 'log_12',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 11:45:10',
    timeAgo: '3시간 전',
    influencer: {
      handle: 'minimal_haru',
      nickname: '미니멀하루',
      profileUrl: 'https://instagram.com/minimal_haru',
      followers: '52.1K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email',
    secondMessageSent: true,
    memo: '피드 2회 포스팅 확정 (9/20 예정)',
  },
  {
    id: 'log_13',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 10:30:20',
    timeAgo: '4시간 전',
    influencer: {
      handle: 'street_snap_kr',
      nickname: '스트릿스냅',
      profileUrl: 'https://instagram.com/street_snap_kr',
      followers: '28.4K',
      verified: false,
    },
    status: 'in_talks',
    channel: 'none',
    secondMessageSent: false,
    memo: '협업 가이드 확인 후 오늘 중 회신 예정',
  },
  {
    id: 'log_14',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-14 09:15:00',
    timeAgo: '5시간 전',
    influencer: {
      handle: 'seoul_vibe_fit',
      nickname: '서울바이브',
      profileUrl: 'https://instagram.com/seoul_vibe_fit',
      followers: '63.2K',
      verified: true,
    },
    status: 'in_talks',
    channel: 'email',
    secondMessageSent: true,
    memo: '제작 일정 조율 중',
  },
  {
    id: 'log_15',
    projectId: 'proj_1',
    projectName: '24년 가을 신상품 협업 제안',
    timestamp: '2026-09-13 18:20:00',
    timeAgo: '어제',
    influencer: {
      handle: 'lookbook_jina',
      nickname: '지나',
      profileUrl: 'https://instagram.com/lookbook_jina',
      followers: '77.5K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email_inpock',
    secondMessageSent: true,
    memo: '계약서 서명 완료, 제품 출고 요청',
  },

  // --- proj_2 (6건) ---
  {
    id: 'log_2',
    projectId: 'proj_2',
    projectName: '뷰티 라인업 앰버서더 2기',
    timestamp: '2026-09-14 14:33:05',
    timeAgo: '6분 전',
    influencer: {
      handle: 'beauty_som',
      nickname: '솜',
      profileUrl: 'https://instagram.com/beauty_som',
      followers: '128K',
      verified: true,
    },
    status: 'in_talks',
    channel: 'email',
    secondMessageSent: true,
    memo: '원고료 추가 협의 필요 (답변 대기)',
  },
  {
    id: 'log_8',
    projectId: 'proj_2',
    projectName: '뷰티 라인업 앰버서더 2기',
    timestamp: '2026-09-14 13:15:33',
    timeAgo: '1시간 전',
    influencer: {
      handle: 'beauty_hye',
      nickname: '혜',
      profileUrl: 'https://instagram.com/beauty_hye',
      followers: '31.5K',
      verified: false,
    },
    status: 'in_talks',
    channel: 'inpock',
    secondMessageSent: false,
    memo: '샘플 발송 주소지 수신 대기',
  },
  {
    id: 'log_16',
    projectId: 'proj_2',
    projectName: '뷰티 라인업 앰버서더 2기',
    timestamp: '2026-09-14 11:20:00',
    timeAgo: '3시간 전',
    influencer: {
      handle: 'glow_creator_y',
      nickname: '글로우Y',
      profileUrl: 'https://instagram.com/glow_creator_y',
      followers: '84.0K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email_inpock',
    secondMessageSent: true,
    memo: '수분 진정 앰플 체험단 리뷰 확정',
  },
  {
    id: 'log_17',
    projectId: 'proj_2',
    projectName: '뷰티 라인업 앰버서더 2기',
    timestamp: '2026-09-14 10:05:00',
    timeAgo: '4시간 전',
    influencer: {
      handle: 'skin_recipe_m',
      nickname: '스킨레시피',
      profileUrl: 'https://instagram.com/skin_recipe_m',
      followers: '42.9K',
      verified: false,
    },
    status: 'in_talks',
    channel: 'email',
    secondMessageSent: false,
    memo: '피부 타입 확인 및 앰플 전성분 자료 전달',
  },
  {
    id: 'log_18',
    projectId: 'proj_2',
    projectName: '뷰티 라인업 앰버서더 2기',
    timestamp: '2026-09-13 16:40:00',
    timeAgo: '어제',
    influencer: {
      handle: 'cosmetic_queen',
      nickname: '코스메틱퀸',
      profileUrl: 'https://instagram.com/cosmetic_queen',
      followers: '145K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email_inpock',
    secondMessageSent: true,
    memo: '앰버서더 3개월 정기 계약 체결',
  },
  {
    id: 'log_19',
    projectId: 'proj_2',
    projectName: '뷰티 라인업 앰버서더 2기',
    timestamp: '2026-09-13 14:10:00',
    timeAgo: '어제',
    influencer: {
      handle: 'k_beauty_yun',
      nickname: '윤',
      profileUrl: 'https://instagram.com/k_beauty_yun',
      followers: '21.0K',
      verified: false,
    },
    status: 'waiting',
    channel: 'none',
    secondMessageSent: false,
    memo: '최초 제안 DM 발송 완료 (미확인)',
  },

  // --- proj_3 (5건) ---
  {
    id: 'log_4',
    projectId: 'proj_3',
    projectName: 'F/W 시즌 아우터 인플루언서 시딩',
    timestamp: '2026-09-14 14:11:18',
    timeAgo: '28분 전',
    influencer: {
      handle: 'urban_lookbook',
      nickname: '어반룩북',
      profileUrl: 'https://instagram.com/urban_lookbook',
      followers: '89.3K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'inpock',
    secondMessageSent: true,
    memo: 'F/W 아우터 착장 2세트 발송 완료',
  },
  {
    id: 'log_6',
    projectId: 'proj_3',
    projectName: 'F/W 시즌 아우터 인플루언서 시딩',
    timestamp: '2026-09-14 13:44:02',
    timeAgo: '55분 전',
    influencer: {
      handle: 'daily_look_j',
      nickname: '제이',
      profileUrl: 'https://instagram.com/daily_look_j',
      followers: '62.8K',
      verified: true,
    },
    status: 'in_talks',
    channel: 'none',
    secondMessageSent: true,
    memo: '제품 컬러 옵션 선호도 확인 중 (블랙 L사이즈 희망)',
  },
  {
    id: 'log_20',
    projectId: 'proj_3',
    projectName: 'F/W 시즌 아우터 인플루언서 시딩',
    timestamp: '2026-09-14 11:00:00',
    timeAgo: '3시간 전',
    influencer: {
      handle: 'outer_fit_master',
      nickname: '아우터핏마스터',
      profileUrl: 'https://instagram.com/outer_fit_master',
      followers: '73.4K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email',
    secondMessageSent: true,
    memo: '패딩 코디 피드 업로드 일정 합의 완료',
  },
  {
    id: 'log_21',
    projectId: 'proj_3',
    projectName: 'F/W 시즌 아우터 인플루언서 시딩',
    timestamp: '2026-09-14 09:40:00',
    timeAgo: '5시간 전',
    influencer: {
      handle: 'winter_style_k',
      nickname: '윈터스타일K',
      profileUrl: 'https://instagram.com/winter_style_k',
      followers: '35.6K',
      verified: false,
    },
    status: 'in_talks',
    channel: 'inpock',
    secondMessageSent: false,
    memo: '원고료 및 가이드 조율 중',
  },
  {
    id: 'log_22',
    projectId: 'proj_3',
    projectName: 'F/W 시즌 아우터 인플루언서 시딩',
    timestamp: '2026-09-13 17:30:00',
    timeAgo: '어제',
    influencer: {
      handle: 'mens_ootd_archive',
      nickname: '멘즈오오티디',
      profileUrl: 'https://instagram.com/mens_ootd_archive',
      followers: '18.9K',
      verified: false,
    },
    status: 'waiting',
    channel: 'none',
    secondMessageSent: false,
    memo: 'DM 발송 후 읽음 확인 대기',
  },

  // --- proj_4 (4건) ---
  {
    id: 'log_10',
    projectId: 'proj_4',
    projectName: '추석 얼리버드 앰버서더',
    timestamp: '2026-09-14 12:49:15',
    timeAgo: '2시간 전',
    influencer: {
      handle: 'seoul_look_archive',
      nickname: '서울룩아카이브',
      profileUrl: 'https://instagram.com/seoul_look_archive',
      followers: '112K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'none',
    secondMessageSent: true,
    memo: '앰버서더 계약서 날인 대기',
  },
  {
    id: 'log_23',
    projectId: 'proj_4',
    projectName: '추석 얼리버드 앰버서더',
    timestamp: '2026-09-14 10:15:00',
    timeAgo: '4시간 전',
    influencer: {
      handle: 'lifestyle_haru',
      nickname: '라이프스타일하루',
      profileUrl: 'https://instagram.com/lifestyle_haru',
      followers: '96.2K',
      verified: true,
    },
    status: 'confirmed',
    channel: 'email_inpock',
    secondMessageSent: true,
    memo: '추석 선물세트 언박싱 릴스 확정',
  },
  {
    id: 'log_24',
    projectId: 'proj_4',
    projectName: '추석 얼리버드 앰버서더',
    timestamp: '2026-09-13 15:50:00',
    timeAgo: '어제',
    influencer: {
      handle: 'wellness_diary',
      nickname: '웰니스다이어리',
      profileUrl: 'https://instagram.com/wellness_diary',
      followers: '48.3K',
      verified: false,
    },
    status: 'in_talks',
    channel: 'email',
    secondMessageSent: true,
    memo: '선물세트 패키지 구성 확인 중',
  },
  {
    id: 'log_25',
    projectId: 'proj_4',
    projectName: '추석 얼리버드 앰버서더',
    timestamp: '2026-09-13 11:30:00',
    timeAgo: '어제',
    influencer: {
      handle: 'gift_curator_ss',
      nickname: '기프트큐레이터',
      profileUrl: 'https://instagram.com/gift_curator_ss',
      followers: '29.7K',
      verified: false,
    },
    status: 'waiting',
    channel: 'none',
    secondMessageSent: false,
    memo: '제안 DM 발송 완료 (익일 리마인드 예정)',
  },
];
